#!/usr/bin/env python3
"""
Space Vikings File Format Analysis
Comprehensive summary of all discovered file formats
"""

def create_summary():
    print('SPACE VIKINGS FILE FORMAT ANALYSIS')
    print('=' * 70)
    print()
    
    print('1. BASIC OVERLAY SYSTEM')
    print('   - 10 overlays with 22 transitions')
    print('   - Files intentionally overlap in memory (shared state)')
    print('   - Must use BLOAD addresses from START.bas, not catalog addresses')
    print()
    
    print('2. GAME STATE FILES')
    print()
    
    print('   A. P_F.payload.bin (320 bytes)')
    print('      - 20 records of 16 bytes each')
    print('      - Load address: $97E1')
    print('      - Structure per record:')
    print('        * Bytes 0-1: Word value A (little-endian)')
    print('        * Bytes 2-3: Word value B (little-endian)')
    print('        * Byte 4:    Flag (0 or 1)')
    print('        * Byte 5:    Record ID (1-20)')
    print('        * Bytes 6-15: Additional data (usually zeros)')
    print('      - Appears to be planet/starbase data (prices, availability?)')
    print('      - Records with flag=1: IDs 1,4,7,8,11,12,15')
    print('      - Records with flag=0: IDs 2,3,5,6,9,10,13,14,16,17,18,19,20')
    print()
    
    print('   B. PLANET FILE.payload.bin (175 bytes)')
    print('      - Load address: $954C')
    print('      - Contains FF FF 01 01 repeated pattern (uninitialized)')
    print('      - PLANET FILE-M.payload.bin (template) has structured data')
    print('      - PLANET FILE-M structure:')
    print('        * Byte 0: 01 (likely planet count or index)')
    print('        * Byte 21: 01 (matches P_F record 0 byte 4)')
    print('        * Bytes 32+: Various data values')
    print('      - Likely contains current planet state/visited status')
    print()
    
    print('   C. SHIP\'S DATA-M.payload.bin (54 bytes)')
    print('      - Load address: $38150')
    print('      - Contains ship statistics:')
    print('        * Offset 0x04-0x05: 1536 (0x0600)')
    print('        * Offset 0x06-0x07: 30795 (0x784B) - large value')
    print('        * Offset 0x08-0x09: 5170 (0x1432)')
    print('        * Offset 0x0A-0x0B: 1 (0x0001)')
    print('        * Offset 0x0E-0x0F: 512 (0x0200)')
    print('        * Offset 0x10-0x11: 771 (0x0303)')
    print('      - Appears to be ship capabilities/upgrades')
    print()
    
    print('   D. SHIP files (shape tables)')
    print('      - SHIP no 0.payload.bin: 1 byte (7F) - placeholder/index')
    print('      - SHIP no 1,3,4.payload.bin: Shape tables starting with 04 00 (5 shapes)')
    print('      - Load address: $8000 (graphics memory)')
    print('      - Format matches Apple II shape table standard')
    print()
    
    print('3. GRAPHICS FORMAT (Apple II Shape Tables)')
    print('   - First byte = number of shapes minus 1')
    print('   - Followed by offsets to each shape\'s data')
    print('   - Shape encoding:')
    print('     * Direction: 0=Right, 1=Up-Right, 2=Up, 3=Up-Left, 4=Left, 5=Down-Left, 6=Down, 7=Down-Right')
    print('     * Steps: Encoded as 1-15, with 0 meaning 16 steps')
    print('     * Pen status: Bit 0 = 1 means move without drawing, 0 means draw line')
    print('     * Terminator: $00 byte ends each shape')
    print('   - Successfully converted 26 files to JSON/SVG')
    print()
    
    print('4. COPY PROTECTION MECHANISM')
    print('   - Checks memory at $95F7 (38391 decimal) for value 77 (ASCII \'M\')')
    print('   - On original disk, $95F7 contains \'M\', triggering BSAVE attempt')
    print('   - The 4am crack modified only 4 bytes:')
    print('     * T00,S02,$FC: DA -> AD')
    print('     * T00,S03,$35: ED -> DE')
    print('     * T00,S02,$5D: DA -> AD')
    print('     * T00,S02,$9E: ED -> DE')
    print()
    
    print('5. MEMORY TRANSFER ROUTINE')
    print('   - MEM TRANSFER A at $9400')
    print('   - Copies 216-byte blocks between $8BEC and $8D7C tables')
    print('   - Uses $9532 as counter index (up to 128 iterations')
    print('   - Likely transfers game state between memory areas')
    print()
    
    print('6. GAME SAVE SEQUENCE (from END.bas)')
    print('   - Saves THREE files:')
    print('     * BSAVE P/F,A$97E1,L$140')
    print('     * BSAVE PLANET FILE,A$954C,L$AF')
    print('     * BSAVE SHIP\'S DATA,A$38150,L$36')
    print('   - Before saving, copies data from $29467-$29475 to $38211-$38219')
    print('   - ORBIT.bas loads PLANET #n (planet shape graphics) at $29440')
    print()
    
    print('7. ASSEMBLY ROUTINES')
    print('   - SPACE SIMULATOR ASSEMBLY ($9023): Game state checks at $95FD-$95FE')
    print('   - SOUND GEN ($9276): Sound generation with Apple II speaker at $C030')
    print('   - EXPL ($9100): Explosion sound effects')
    print('   - LASER ($92D1): Laser effect routines')
    print('   - TRANLIT.OBJ0 ($9600): Unknown translation/transition object')
    print()
    
    print('NEXT STEPS FOR MODERN REMAKE:')
    print('   1. Create JSON schema for P_F/PLANET FILE/SHIP\'S DATA formats')
    print('   2. Implement basic emulator to validate file loading/saving')
    print('   3. Map complete game state between overlays')
    print('   4. Recreate game mechanics in modern JavaScript/Python')
    print('   5. Integrate converted graphics (JSON/SVG)')
    print('   6. Implement original game flow with modern UI')
    
    print()
    print('-' * 70)
    print('SUMMARY:')
    print('- All 42 binaries successfully disassembled')
    print('- 26 graphics files converted to modern JSON/SVG format')
    print('- Game state file formats analyzed (P_F, PLANET FILE, SHIP\'S DATA)')
    print('- Copy protection mechanism documented')
    print('- Repository created and pushed to GitHub')
    print('- Ready for modern remake implementation')

if __name__ == '__main__':
    create_summary()